### ISSUE TITLE
Plans to integrate Kerberos module

### ISSUE THREAD

**Issue by simon-p-r** [abbr/NodeSSPI#37]
Hello @abbr 

Is there any technical reason's why Kerberos security package is not included? Also how do you test module without client implementation.  So far when testing this module I have not been able to successfully authenticate even though it passes with other negotiate testing tools in my environment.

Thanks
Simon

**Comment by abbr** [comment]
There are some technical complexities why Kerberos is not included but one contributing factor is seemly lacking of popularity that Kerberos being used as web app authentication protocol, based both from my personal experience and from the fact that even SharePoint is not using Kerberos by default. The argument is further derived from the fact that only organizations named their AD domain same as their Internet domain can apply Kerberos auth to all of their web sites, otherwise only intranet sites work. Well established orgs usually didn't have a name match for historic reason.

I don't know what you mean by client. To me client is a existing browser without my need to implement.

**Comment by simon-p-r** [comment]
I mean a client could be a desktop app using windows auth without basic authentication, anyway thank you for your comments. If I can find a way to add Kerberos I will make a PR for it.

**Comment by simon-p-r** [comment]
I mean a client could be a desktop app using windows auth without basic authentication, anyway thank you for your comments. If I can find a way to add Kerberos I will make a PR for it.
