### ISSUE TITLE
Switch to n-api

### ISSUE THREAD

**Issue by abbr** [abbr/NodeSSPI#73]
V8 api's backward incompatibility is exacerbated in Node 12. Supporting new Node versions by recompile only is no longer achievable using Nan. Switching to n-api is needed.

**Comment by PowrSlave** [comment]
What?

**Comment by oldrich-s** [comment]
There is a tool to convert Nan to n-api:

https://github.com/nodejs/node-addon-api/tree/master/tools

**Comment by sagitsofan** [comment]
@abbr When can we expect a new release with support of node 12?

**Comment by 6sigmadc** [comment]
@abbr I have attempted to convert this amazing tool from Nan to n-api. It seems to work for me in Node v12. Would you mind have a look and see if that is good for PR?

Although, if you use this n-api version of node-sspi with older NodeJS (like v10) it would not compile -  due to NodeJS v10 uses node-gyp 3.8 internally to build things after npm install.

`https://github.com/6sigmadc/NodeSSPI/commit/df31bf20953c1bc28d6715994ea22c0b49aee930`

**Comment by abbr** [comment]
Fixed in node-sspi@0.2.6. Big thanks to @6sigmadc!!
